# Project information
site_name: 'Deep Learning Wizard'
site_description: 'We try to make learning deep learning, deep bayesian learning, and deep reinforcement learning math and code easier. Used by thousands.'
site_author: 'Ritchie Ng'
site_url: 'https://www.deeplearningwizard.com/'

# Navigation
nav:
    - Home: index.md
    - About:
      - Intro: home.md
      - About Us: about.md
      - Reviews: review.md
      - AI Pipeline: pipeline.md
      - Consultancy: consultancy.md
    - Deep Learning (CPU/GPU):
      - Introduction: deep_learning/intro.md
      - Course Progression: deep_learning/course_progression.md
      - Matrices: deep_learning/practical_pytorch/pytorch_matrices.md
      - Gradients: deep_learning/practical_pytorch/pytorch_gradients.md
      - Linear Regression: deep_learning/practical_pytorch/pytorch_linear_regression.md
      - Logistic Regression: deep_learning/practical_pytorch/pytorch_logistic_regression.md
      - Feedforward Neural Networks (FNN): deep_learning/practical_pytorch/pytorch_feedforward_neuralnetwork.md
      - Convolutional Neural Networks (CNN): deep_learning/practical_pytorch/pytorch_convolutional_neuralnetwork.md
      - Recurrent Neural Networks (RNN): deep_learning/practical_pytorch/pytorch_recurrent_neuralnetwork.md
      - Long Short Term Memory Neural Networks (LSTM): deep_learning/practical_pytorch/pytorch_lstm_neuralnetwork.md
      - Autoencoders (AE): deep_learning/practical_pytorch/pytorch_autoencoder.md
      - Fully-connected Overcomplete Autoencoder (AE): deep_learning/practical_pytorch/pytorch_fc_overcomplete_ae.md
#      - Fully-connected Undercomplete Autoencoder (AE): deep_learning/practical_pytorch/pytorch_fc_undercomplete_ae.md
#      - Convolutional Overcomplete Variational Autoencoder (VAE): deep_learning/practical_pytorch/pytorch_autoencoder.md
#      - Convolutional Overcomplete Adversarial Autoencoder (AAE): deep_learning/practical_pytorch/pytorch_autoencoder.md
#      - Generative Adversarial Networks (GAN): deep_learning/practical_pytorch/pytorch_autoencoder.md
      - Derivative, Gradient and Jacobian: deep_learning/boosting_models_pytorch/derivative_gradient_jacobian.md
      - Forward- and Backward-propagation and Gradient Descent (From Scratch FNN Regression): deep_learning/boosting_models_pytorch/forwardpropagation_backpropagation_gradientdescent.md
      - From Scratch Logistic Regression Classification: deep_learning/fromscratch/fromscratch_logistic_regression.md
      - From Scratch CNN Classification: deep_learning/fromscratch/fromscratch_cnn.md
#       - From Scratch RNN Classification: deep_learning/fromscratch/fromscratch_rnn_classification.md
#       - From Scratch LSTM Classification: deep_learning/fromscratch/fromscratch_lstm_classification.md
#       - From Scratch AE: deep_learning/fromscratch/fromscratch_ae_classification.md
      - Learning Rate Scheduling: deep_learning/boosting_models_pytorch/lr_scheduling.md
      - Optimization Algorithms: deep_learning/boosting_models_pytorch/optimizers.md
      - Weight Initialization and Activation Functions: deep_learning/boosting_models_pytorch/weight_initialization_activation_functions.md
      - Supervised Learning to Reinforcement Learning (RL): deep_learning/deep_reinforcement_learning_pytorch/supervised_to_rl.md
      - Markov Decision Processes (MDP) and Bellman Equations: deep_learning/deep_reinforcement_learning_pytorch/bellman_mdp.md
      - Dynamic Programming: deep_learning/deep_reinforcement_learning_pytorch/dynamic_programming_frozenlake.md
      - Speed Optimization Basics Numba: deep_learning/production_pytorch/speed_optimization_basics_numba.md
      - Additional Readings: deep_learning/readings.md

    - Machine Learning (CPU/GPU):
      - Introduction: machine_learning/intro.md
      - GPU DataFrames: machine_learning/gpu/rapids_cudf.md
      - GPU/CPU Fractional Differencing: machine_learning/gpu/gpu_fractional_differencing.md
#      - Linear Regression: machine_learning/gpu/rapids_cudf.md
#      - Ridge Regression: machine_learning/gpu/rapids_cudf.md
#      - Kalman Filter: machine_learning/gpu/rapids_cudf.md
#      - Stochastic Gradient Descent: machine_learning/gpu/rapids_cudf.md
#      - K-nearest Neighbours Classification: machine_learning/gpu/rapids_cudf.md
#      - K-Means Clustering: machine_learning/gpu/rapids_cudf.md
#      - Density-Based Spatial Clustering of Applications with Noise (DBSCAN): machine_learning/gpu/rapids_cudf.md
#      - Singular Value Decomposition (SVD), Dimensionality Reduction: machine_learning/gpu/rapids_cudf.md
#      - Principal Component Analysis (PCA), Dimensionality Reduction: machine_learning/gpu/rapids_cudf.md
#      - Uniform Manifold Approximation and Projection (UMAP), Dimensionality Reduction: machine_learning/gpu/rapids_cudf.md

    - Programming:
      - Introduction: programming/intro.md
      - C++: programming/cpp/cpp.md
      - Bash: programming/bash/bash.md
      - Python: programming/python/python.md
      - Javascript: programming/javascript/javascript.md
      - Electron: programming/electron/electron.md
#      - Matplotlib: programming/plotting/matplotlib.md

    # - Plotting:
    #   - Introduction: programming/plotting/intro.md

    - Out of Distribution Data:
      - Introduction: ood/intro.md

    - Scalable Database:
      - Introduction: database/intro.md
      - Cassandra Cluster Setup: database/setting_up_cluster.md

    - News:
      - Welcome: news/news.md
      - Fractional Differencing with GPU (GFD), DBS and NVIDIA, September 2019: news/dbs_gpu_rapids_nvidia_ensemble_frac_diff.md
      - Deep Learning Introduction, Defence and Science Technology Agency (DSTA) and NVIDIA, June 2019: news/defence_and_science_technology_agency_dsta_nvidia_talk_2016_06.md
      - Oral Presentation for AI for Social Good Workshop ICML, June 2019: news/detect_waterbone_debris_ai_for_social_good_icml_2019_06.md
      - IT Youth Leader of The Year 2019, March 2019: news/it_youth_leader_2019_03_11.md
      - AMMI (AIMS) supported by Facebook and Google, November 2018: news/ammi_facebook_google_recap_2018_11_21.md
      - NExT++ AI in Healthcare and Finance, Nanjing, November 2018: news/nanjing_next_nus_tsinghua_ai_finance_healthcare_2018_11_01.md
      - Recap of Facebook PyTorch Developer Conference, San Francisco, September 2018: news/facebook_pytorch_devcon_recap_2018_10_02.md
      - Facebook PyTorch Developer Conference, San Francisco, September 2018: news/facebook_pytorch_developer_conference_2018_09_05.md
      - NUS-MIT-NUHS NVIDIA Image Recognition Workshop, Singapore, July 2018: news/nvidia_nus_mit_datathon_2018_07_05.md
      - Featured on PyTorch Website 2018: news/deep_learning_wizard_1y_2018_06_01.md
      - NVIDIA Self Driving Cars & Healthcare Talk, Singapore, June 2017: news/nvidia_self_driving_cars_talk_2017_06_21.md
      - NVIDIA Inception Partner Status, Singapore, May 2017: news/deep_learning_wizard_nvidia_inception_2018_05_01.md

# Configuration
theme:
  name: 'material'
  custom_dir: 'material'
  # 404 page
  static_templates:
    - 404.html
  language: 'en'
  features:
    - navigation.tabs
    - instant
  icon:
    logo: 'fontawesome/regular/chart-bar'
  palette:
    scheme: default
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: './docs/assets/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid-experimental
  #         format: !!python/name:pymdownx.superfences.fence_code_format

# Equations
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Social
extra:
  social:
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/channel/UCJz2MIjiCosOQCwhnsYxeEw'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/deeplearningwiz'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/DeepLearningWizard/'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/deeplearningwizard/'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/ritchieng'
  disqus: 'deep-learning-wizard'

# Search
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang: 
        - en
  # - minify:
  #     minify_html: true

# Google Analytics
google_analytics:
  - 'UA-122083328-1'
  - 'auto'

# Source to repository
repo_name: ritchieng/deep-learning-wizard
repo_url: https://github.com/ritchieng/deep-learning-wizard

# Copyright
copyright: 'Copyright &copy; 2021 Deep Learning Wizard by Ritchie Ng'
